config/routes.rb
Prospect::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :interests, only: [:create, :destroy]
  root :to => "home#index"
  match "/contact", to: "home#contact"
  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: "delete"

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  attr_accessible :name, :status, :notes
  validates :user_id, presence: true
  validates :name, presence: true, length: {maximum: 30}
  validates :status, presence: true, length: { maximum: 140 }
  belongs_to :user
  default_scope order: 'interests.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password
  has_secure_password
  has_many :interests, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Prospect"
    @user = current_user
    @interest = current_user.interests.build if signed_in?
  end
  def contact
  
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @interest = current_user.interests.build(params[:interest])
    if @interest.save
      flash[:success] = "Interest created!"
      redirect_to root_url
    else
      render 'home/index'
    end
  end

  def destroy
    @interest.destroy
    redirect_to root_url
  end
  
  private

    def correct_user
      @interest = current_user.interests.find_by_id(params[:id])
      redirect_to root_url if @interest.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:show, :edit, :update, :destroy]
  before_filter :admin_user,     only: :destroy
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])

    @interests = @user.interests.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Prospect!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
   
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
#  def index
#    @users = User.paginate(page: params[:page])
#  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  
  private
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/contact.html.erb
<div class="center hero-unit">
  <h1Contact Us/h1>

  <h2>
    This is a place holder for contact us information.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/home/index.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/interest_form' %>
      </section>
    </aside>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Prospect</h1>

    <h2>
	  Prospect allows you to keep track of your dating prospects so you never forget to <%= link_to "communicate", "http://www.google.com" %> with them
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/interests/_interest.html.erb
<% if current_user?(interest.user) %>
<tr>
  <td><%= "#{interest.name}" %></td>
  <td><%= "#{interest.status}" %></td>
  <td><%= "#{interest.notes}" %></td>
  <td><span class="timestamp">
    Posted <%= time_ago_in_words(interest.created_at) %> ago.</span>
  </td>
  <td>
    <%= link_to "delete", interest, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: interest.name %>
  </td>
</tr>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Prospect" , root_path %>
    by <%= link_to "Yash Ranadive", "http://www.about.me/yash.ranadive" %>
  </small>
  <nav>
    <ul>
      <li></li>
      <li></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
	  <%= link_to "Prospect", :root, id: "logo" %>
	  <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <!--<li><%= link_to "Users", users_path %></li>-->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
	</div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%#<title><%= full_title(yield(:title)) %>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
	<%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_interest_form.html.erb
<%= form_for(@interest) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Name..." %>
    <%= f.text_field :status, placeholder: "Status..." %>
    <%= f.text_field :notes, placeholder: "Notes..." %>
  </div>
  <%= f.submit "Add Interest", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <h1>
    <%= current_user.name %>
  </h1>  
</a>

<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.interests.count, "interest") %>
</span>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

   <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside>
    <%= @user.name %>, <%= @user.email %>
  </aside>
  <div class="span8">
    <% if @user.interests.any? %>
      <h3>Prospects (<%= @user.interests.count %>)</h3>
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <%= render @interests %>
        </tbody>
      </table>
      <%= will_paginate @interests %>
    <% end %>
  </div>
</div>